spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password # Use Google App Passwords, not your login password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true