spring:
  cloud:
    gateway:
      httpclient:               # Configuration properties for the HTTP client
        connect-timeout: 2000   # 2s  Time limit for a connection to be established (in ms)
        response-timeout: 5s    # Time limit for a response to be received (Duration)
        pool:
          type: elastic         # Type of connection pool (elastic, fixed, or disabled)
          max-idle-time: 15s    # Idle time after which the communication channel will be closed
          max-life-time: 60s    # Time after which the communication channel will be closed
      default-filters:                # A list of default filters
        - name: Retry                 # The name of the filter
          args:
            retries: 3                # Maximum of 3 retry attempts
            methods: GET              # Retries only GET requests
            series: SERVER_ERROR      # Retries only when 5XX errors
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException  # Retries only when the given exceptions are thrown
            backoff:                  # Retries with a delay computed as “firstBackoff * (factor ^ n)”
              firstBackoff: 50ms
              maxBackOff: 500ms
              factor: 2
              basedOnPreviousValue: false
      routes:                                   # A list of route definitions
        - id: student-service                     # The route ID
          uri: http://localhost:9001 # The URI value comes from an environment variable, or else from the default.
          filters:
            - name: CircuitBreaker                      # Name of the filter
              args:
                name: studentServiceCircuitBreaker             # Name of the circuit breaker
                fallbackUri: forward:/student-service-fallback  # Forwards request to this URI when the circuit is open
            - name: FallbackHeaders # Capture the exception details
              args:
                executionExceptionTypeHeaderName: X-Exception-Type
                executionExceptionMessageHeaderName: X-Exception-Message
          predicates:
            - name: Path
              args:
                patterns:
                  - "/student-service/api/students/**"
                  - "/student-service/v3/api-docs"
        - id: payment-service
          uri: http://localhost:9002
          filters:
            - name: CircuitBreaker                    # No fallback defined for this circuit breaker.
              args:
                name: paymentServiceCircuitBreaker             # Multiplier to compute the next interval
                fallbackUri: forward:/payment-service-fallback  # Forwards request to this URI when the circuit is open
            - name: FallbackHeaders # Capture the exception details
              args:
                executionExceptionTypeHeaderName: X-Exception-Type
                executionExceptionMessageHeaderName: X-Exception-Message
          predicates:
            - name: Path
              args:
                patterns:
                  - "/payment-service/api/payments/**"
                  - "/payment-service/v3/api-docs" 
        - id: notification-service
          uri: http://localhost:9003
          filters:
            - name: CircuitBreaker                    # No fallback defined for this circuit breaker.
              args:
                name: notificationServiceCircuitBreaker             # Multiplier to compute the next interval
                fallbackUri: forward:/notification-service-fallback  # Forwards request to this URI when the circuit is open
            - name: FallbackHeaders # Capture the exception details
              args:
                executionExceptionTypeHeaderName: X-Exception-Type
                executionExceptionMessageHeaderName: X-Exception-Message
          predicates:
            - name: Path
              args:
                patterns:
                  - "/notification-service/api/notifications/**"
                  - "/notification-service/v3/api-docs"
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"